# Generated by Django 6.0.3 on 2026-03-15 18:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Dealer company name', max_length=200)),
                ('latitude', models.FloatField(blank=True, help_text='Current GPS latitude', null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(blank=True, help_text='Current GPS longitude', null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('coverage_radius_km', models.FloatField(default=10.0, help_text='Delivery coverage radius in kilometers', validators=[django.core.validators.MinValueValidator(0.1)])),
                ('is_available', models.BooleanField(default=True, help_text='Whether dealer is online and accepting orders')),
                ('bio', models.TextField(blank=True, help_text='Dealer bio and description')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, help_text='Average rating (0-5)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturers', models.ManyToManyField(blank=True, help_text='Manufacturers this dealer works with', limit_choices_to={'role': 'manufacturer'}, related_name='dealers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='Associated dealer user', on_delete=django.db.models.deletion.CASCADE, related_name='dealer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dealer Profile',
                'verbose_name_plural': 'Dealer Profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_available', '-rating'], name='dealers_dea_is_avai_482e7b_idx'), models.Index(fields=['user'], name='dealers_dea_user_id_c7d5d3_idx')],
            },
        ),
    ]
